export const Massive = [
  { name: "John", age: 28, city: "New York" },
  { name: "Emily", age: 22, city: "Los Angeles" },
  { name: "Michael", age: 30, city: "Chicago" },
  { name: "Sophia", age: 26, city: "San Francisco" },
  { name: "William", age: 27, city: "Seattle" },
  { name: "Olivia", age: 24, city: "Boston" },
  { name: "Daniel", age: 29, city: "Miami" },
  { name: "Ava", age: 23, city: "Denver" },
  { name: "Matthew", age: 31, city: "Austin" },
  { name: "Emma", age: 25, city: "Portland" },
  { name: "Christopher", age: 28, city: "San Diego" },
  { name: "Isabella", age: 27, city: "Phoenix" },
  { name: "Ethan", age: 26, city: "Dallas" },
  { name: "Mia", age: 29, city: "Houston" },
  { name: "Alexander", age: 24, city: "Atlanta" },
];
