import book1 from "../assets/img/book1.jpg";
import book2 from "../assets/img/book2.jpg";
import book3 from "../assets/img/book3.jpg";
import book4 from "../assets/img/book4.jpg";
import book5 from "../assets/img/book 5.jpg";
import book6 from "../assets/img/book6.jpg";
export const CardContent = [
  {
    image: book1,
    name: "The Lord of the Rings",
    price: "1200 ",
    count: 1,
    status: false,
    favorite: false,
    id: 1,
    fishka: "new",
    titul: "hit",
  },
  {
    image: book2,
    name: "Shantaram",
    price: "1300 ",
    count: 1,
    status: false,
    favorite: false,
    id: 2,
    titul: "hit",
  },
  {
    image: book3,
    name: "451 fahrenheit",
    price: "999 ",
    count: 1,
    status: false,
    favorite: false,
    id: 3,
    fishka: "new",
  },
  {
    image: book4,
    name: "The Art of War",
    price: "750 ",
    count: 1,
    status: false,
    favorite: false,
    id: 4,
    fishka: "new",
  },
  {
    image: book5,
    name: "Mystery Island",
    price: "1200 ",
    count: 1,
    status: false,
    favorite: false,
    titul: "hit",
  },
  {
    image: book6,
    name: "Three Comrades",
    price: "1200 ",
    count: 1,
    status: false,
    favorite: false,
    fishka: "new",
    titul: "hit",
  },
  {
    image: book1,
    name: "The Lord of the Rings",
    price: "1200 ",
    count: 1,
    status: false,
    favorite: false,
    fishka: "new",
  },
  {
    image: book1,
    name: "The Lord of the Rings",
    price: "1200 ",
    count: 1,
    status: false,
    favorite: false,
    fishka: "new",
  },
  {
    image: book1,
    name: "The Lord of the Rings",
    price: "1200 ",
    count: 1,
    status: false,
    favorite: false,
    fishka: "new",
  },
  {
    image: book1,
    name: "The Lord of the Rings",
    price: "1200 ",
    count: 1,
    status: false,
    favorite: false,
  },
  {
    image: book1,
    name: "The Lord of the Rings",
    price: "1200 ",
    count: 1,
    status: false,
    favorite: false,
  },
  {
    image: book1,
    name: "The Lord of the Rings",
    price: "1200 ",
    count: 1,
    status: false,
    favorite: false,
    fishka: "new",
  },
];
