import book1 from "../assets/img/book1.jpg";
import book2 from "../assets/img/book2.jpg";
import book3 from "../assets/img/book3.jpg";
import book4 from "../assets/img/book4.jpg";
import book5 from "../assets/img/book 5.jpg";
import book6 from "../assets/img/book6.jpg";

import book8 from "../assets/img/book8.jpg";
export const CardContent = [
  {
    transferButton: false,
    image: book8,
    name: "The Witcher",
    price: "210 ",
    count: 1,
    status: false,
    isFavorite: false,
    id: 1,
    fishka: "new",
    titul: "hit",
  },
  {
    transferButton: false,
    image: book1,
    name: "The Lord of the Rings",
    price: "430 ",
    count: 1,
    status: false,
    isFavorite: false,
    id: 2,
    fishka: "new",
    titul: "hit",
  },
  {
    transferButton: false,
    image: book2,
    name: "Shantaram",
    price: "312 ",
    count: 1,
    status: false,
    isFavorite: false,
    id: 3,
    titul: "hit",
  },
  {
    transferButton: false,
    image: book3,
    name: "451 fahrenheit",
    price: "154 ",
    count: 1,
    status: false,
    isFavorite: false,
    id: 4,
    fishka: "new",
  },
  {
    transferButton: false,
    image: book4,
    name: "The Art of War",
    price: "130 ",
    count: 1,
    status: false,
    isFavorite: false,
    id: 5,
    fishka: "new",
  },
  {
    transferButton: false,
    image: book5,
    name: "Mystery Island",
    price: "210 ",
    count: 1,
    status: false,
    isFavorite: false,
    id: 6,
    titul: "hit",
  },
  {
    transferButton: false,
    image: book6,
    name: "Three Comrades",
    price: "340 ",
    count: 1,
    status: false,
    isFavorite: false,
    id: 7,
    fishka: "new",
    titul: "hit",
  },
  {
    transferButton: false,
    image: book1,
    name: "The Lord of the Rings",
    price: "215 ",
    count: 1,
    status: false,
    isFavorite: false,
    id: 8,
    fishka: "new",
  },
  {
    transferButton: false,
    image: book1,
    name: "The Lord of the Rings",
    price: "1200 ",
    count: 1,
    status: false,
    isFavorite: false,
    id: 9,
    fishka: "new",
  },
  {
    transferButton: false,
    image: book1,
    name: "The Lord of the Rings",
    price: "1200 ",
    count: 1,
    status: false,
    id: 10,
    isFavorite: false,
    fishka: "new",
  },
  {
    transferButton: false,
    image: book1,
    name: "The Lord of the Rings",
    price: "1200 ",
    count: 1,
    id: 11,
    status: false,
    isFavorite: false,
  },
  {
    transferButton: false,
    image: book1,
    name: "The Lord of the Rings",
    price: "1200 ",
    count: 1,
    id: 12,
    status: false,
    isFavorite: false,
  },
  {
    transferButton: false,
    image: book1,
    name: "The Lord of the Rings",
    price: "1200 ",
    count: 1,
    id: 13,
    status: false,
    isFavorite: false,
    fishka: "new",
  },
];
